### PR TITLE
[WIP] Add support for attaching projects to VPC Service Control Perimeter

### PR DESCRIPTION
**Pull request by Jberlinsky**

### CODE REVIEW

**Comment by Jberlinsky** [comment]
@morgante Apologies for the delay. Getting this to work will require bumping the minimum required version of the `google` provider to `3.8.0` (when (`google_access_context_manager_service_perimeter_resource` was introduced). It's currently `2.1`. Is that an acceptable change?

**Comment by morgante** [comment]
@Jberlinsky yes that's fine.

**Comment by Jberlinsky** [comment]
@morgante We ran into a race condition with this approach (see b/159054088). I'm going to close this PR out for now, since it invites trouble into this module.

**Comment by morgante** [comment]
@Jberlinsky The linked bug seems to refer to creating a new perimeter, not updating it.

Is there a GitHub issue for the provider which I can track?

**Comment by Jberlinsky** [comment]
There isn't a provider issue filed -- I'll ping you offline to discuss.

**Comment by bharathkkb** [comment]
@Jberlinsky reopening this as someone testing this out.

**Comment by bharathkkb** [comment]
superseded by #428

**Pull request closed without merging**
