### PR TITLE
fix: Add billingbudgets.googleapis.com to precondition script.

### LINKED ISSUE #486: seed project script misses dependency of billing budget feature
```
"billingbudgets.googleapis.com"
```

Should be enabled for the seed project, to avoid an error when provisioning the first project / host-project / service-project.

### PR DESCRIPTION
**Pull request by morgante**
Fixes #486.

### CODE REVIEW

**Comment by thiagonache** [comment]
should we also add check in the preconditions script?

**Comment by morgante** [comment]
@thiagonache No I don't think a check is necessary. The error from this is fairly clear and recoverable.

**Review by bharathkkb — APPROVED** [review]
LGTM
CI failure seems unrelated

**Pull request merged**
