### PR TITLE
fix: shared_vpc resources at folder level is in beta

### PR DESCRIPTION
**Pull request by xingao267**
ref:
* https://cloud.google.com/vpc/docs/provisioning-shared-vpc#enable-shared-vpc-host
* https://cloud.google.com/vpc/docs/provisioning-shared-vpc#create-shared

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.Kmaz0z3Gvt/generate_docs/workspace/README.md
116c116
< | bucket\_labels | A map of key/value label pairs to assign to the bucket (optional) | `map` | `{}` | no |
---
> | bucket\_labels | A map of key/value label pairs to assign to the bucket (optional) | `map(any)` | `{}` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by morgante** [comment]
@xingao267 Does this actually require the beta API? The fields seem to be the same.

**Comment by xingao267** [comment]
> @xingao267 Does this actually require the beta API? The fields seem to be the same.

yea, we recently encountered this error (the service account that tries to enable shared VPC host and service project in a folder gets a 403 permission denied error even it has the folder level Shared VPC Admin role), and after looking into this, the doc says if you have Shared VPC Admin role at the folder level, you need to use `gcloud beta` commands. The folder support is still in beta.

**Review by morgante — APPROVED** [review]

**Comment by ruanda** [comment]
> I'm not sure why it was fine before, as I assume there are tests that cover folder level shared VPCs, but the issues seems just surfaced recently.

Google provider (not beta) before 3.60 actually used beta calls for shared vpc. It was "fixed" in https://github.com/hashicorp/terraform-provider-google/commit/a6f342c6057cf0d3c1d6241b8f91be579aabd8e0#diff-d00da7be384ad2ae0338a4ab6a736a8635ca9d9a9265fc14e6a792865b9214fa

**Comment by xingao267** [comment]
> > I'm not sure why it was fine before, as I assume there are tests that cover folder level shared VPCs, but the issues seems just surfaced recently.
> 
> Google provider (not beta) before 3.60 actually used beta calls for shared vpc. It was "fixed" in [hashicorp/terraform-provider-google@a6f342c#diff-d00da7be384ad2ae0338a4ab6a736a8635ca9d9a9265fc14e6a792865b9214fa](https://github.com/hashicorp/terraform-provider-google/commit/a6f342c6057cf0d3c1d6241b8f91be579aabd8e0#diff-d00da7be384ad2ae0338a4ab6a736a8635ca9d9a9265fc14e6a792865b9214fa)

Thanks for finding the root cause!

**Pull request merged**
