### PR TITLE
Bump provider versions

### PR DESCRIPTION
**Pull request by wmuizelaar**
Also fixes the core_project_factory that still pointed to 2.x

### CODE REVIEW

**Comment by morgante** [comment]
Thanks for the PR. What is the intent with this change? We try not to be overly strict with provider versions if we don't have to, so I'm not sure we need to restrict the provider versions further if we're not depending on a new feature.

**Comment by wmuizelaar** [comment]
The main reason is the change in modules/fabric-project/versions.tf  - that one is needed to be able to use a 3.x.y provider version. Otherwise terraform will complain it could not find a valid version.

**Comment by morgante** [comment]
Got it, thanks. In that case, could we reduce this change to update the examples + that file, while backing out the changes to other module versions?

**Comment by wmuizelaar** [comment]
Sure! Hope to have applied your desired changes with this latest version.

**Pull request merged**
