### PR TITLE
test: enable TF_LOG for CI

### PR DESCRIPTION
**Pull request by apeabody**
---TEST ONLY - DO NOT MERGE---

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/app_engine
Success!
 The configuration is valid.
terraform_validate ./examples/budget_project
Success!
 The configuration is valid.
terraform_validate ./examples/essential_contacts
Success!
 The configuration is valid.
terraform_validate ./examples/fabric_project
Success!
 The configuration is valid.
terraform_validate ./examples/gke_shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/group_project
Success!
 The configuration is valid.
terraform_validate ./examples/project-hierarchy
Success!
 The configuration is valid.
terraform_validate ./examples/project_services
Success!
 The configuration is valid.
terraform_validate ./examples/quota_project
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/simple_project
Success!
 The configuration is valid.
terraform_validate ./modules/app_engine
Success!
 The configuration is valid.
terraform_validate ./modules/budget
Success!
 The configuration is valid.
terraform_validate ./modules/core_project_factory
Success!
 The configuration is valid.
terraform_validate ./modules/essential_contacts
Success!
 The configuration is valid.
terraform_validate ./modules/fabric-project
Success!
 The configuration is valid.
terraform_validate ./modules/gsuite_enabled
Success!
 The configuration is valid.
terraform_validate ./modules/gsuite_group
Success!
 The configuration is valid.
terraform_validate ./modules/project_services
Success!
 The configuration is valid.
terraform_validate ./modules/quota_manager
Success!
 The configuration is valid.
terraform_validate ./modules/shared_vpc_access
Success!
 The configuration is valid.
terraform_validate ./modules/svpc_service_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/app_engine
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/budget
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/dynamic_shared_vpc
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/fabric_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/full
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/minimal
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 18, in provider "google":
│
 
  18:   version = 
"~> 4.5"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and 3 more similar warnings elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/vpc_sc_project
Success!
 The configuration is valid.
terraform_validate ./test/setup
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google-beta: no available releases match the given constraints >=
│
 
3.1.0, ~> 3.8, >= 3.43.0, >= 3.50.0, ~> 4.5, < 5.0.0
╵
╷
│
 
Error: 
Failed to query available provider packages
│
 
│
 
Could not retrieve the list of available versions for provider
│
 
hashicorp/google: no available releases match the given constraints ~> 3.8,
│
 
>= 3.43.0, >= 3.50.0, ~> 4.5, < 5.0.0
╵
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.jQj668Hqh0/generate_docs/workspace/README.md
145c145
< | labels | Map of labels for project | `map(string)` | `{}` | no |
---
> | labels | Map of labels for project | `map(string)` | `[]` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./examples/app_engine
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./examples/budget_project
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./examples/essential_contacts
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./examples/fabric_project
Success!
 The configuration is valid.
terraform_validate ./examples/gke_shared_vpc
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./examples/group_project
Success!
 The configuration is valid.
terraform_validate ./examples/project-hierarchy
Success!
 The configuration is valid.
terraform_validate ./examples/project_services
Success!
 The configuration is valid.
terraform_validate ./examples/quota_project
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./examples/shared_vpc
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./examples/simple_project
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./modules/app_engine
Success!
 The configuration is valid.
terraform_validate ./modules/budget
Success!
 The configuration is valid.
terraform_validate ./modules/core_project_factory
Success!
 The configuration is valid.
terraform_validate ./modules/essential_contacts
Success!
 The configuration is valid.
terraform_validate ./modules/fabric-project
Success!
 The configuration is valid.
terraform_validate ./modules/gsuite_enabled
Success!
 The configuration is valid.
terraform_validate ./modules/gsuite_group
Success!
 The configuration is valid.
terraform_validate ./modules/project_services
Success!
 The configuration is valid.
terraform_validate ./modules/quota_manager
Success!
 The configuration is valid.
terraform_validate ./modules/shared_vpc_access
Success!
 The configuration is valid.
terraform_validate ./modules/svpc_service_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/app_engine
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./test/fixtures/budget
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./test/fixtures/dynamic_shared_vpc
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./test/fixtures/fabric_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/full
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/minimal
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./test/fixtures/vpc_sc_project
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│
 
Error: 
Invalid default value for variable
│
 
│
 
  on ../../../variables.tf line 139, in variable "labels":
│
 
 139:   default     = 
[]
│
 
│
 
This default value is not compatible with the variable's type constraint:
│
 
map of string required.
╵
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/examples/fabric_project/README.md /tmp/tmp.pw3HCZ9dSS/generate_docs/workspace/examples/fabric_project/README.md
10c10
< | activate\_apis | Service APIs to enable. | `list(string)` | <pre>[<br>  "compute.googleapis.com"<br>]</pre> | no |
---
> | activate\_apis | Service APIs to enable. | `list(string)` | <pre>[<br>  "serviceusage.googleapis.com",<br>  "compute.googleapis.com"<br>]</pre> | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by apeabody** [comment]
Failed: 4a26f718
Started on Apr 26, 2022, 12:04:40 PM

 Error: Error creating Budget: googleapi: Error 429: Resource has been exhausted (e.g. check quota).

**Comment by apeabody** [comment]
Failed: 074fe8cb
Started on Apr 26, 2022, 1:18:41 PM

Error: Error creating Contact: googleapi: Error 403: Essential Contacts API has not been used in project [...] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/essentialcontacts.googleapis.com/overview?project=[...] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by apeabody** [comment]
Failed: ee10c717
Started on Apr 26, 2022, 2:01:37 PM

Error: Error creating Budget: googleapi: Error 429: Resource has been exhausted (e.g. check quota).

**Comment by apeabody** [comment]
Failed: d4b904b6
Started on Apr 26, 2022, 2:52:40 PM

Error: Error creating Budget: googleapi: Error 429: Resource has been exhausted (e.g. check quota).

**Comment by apeabody** [comment]
Failed: 3b2a315a
Started on Apr 27, 2022, 7:41:11 AM

Error: Error creating Budget: googleapi: Error 429: Resource has been exhausted (e.g. check quota).

**Comment by apeabody** [comment]
Failed: c40f18b4
Started on Apr 27, 2022, 8:27:50 AM

error: Error when reading or editing BillingBudget [...]: googleapi: Error 403: Cloud Billing Budget API has not been used in project [...] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/billingbudgets.googleapis.com/overview?project=[...] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by apeabody** [comment]
Failed: 4a26f718
Started on Apr 26, 2022, 12:04:40 PM

Error: Error creating Budget: googleapi: Error 429: Resource has been exhausted (e.g. check quota).

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by apeabody** [comment]
Failed: af921380
Started on May 2, 2022, 9:35:25 AM

Error: Error when reading or editing Project [...]: googleapi: Error 403: Cloud Resource Manager API has not been used in project [...] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=[...] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by apeabody** [comment]
Successful: 74ca872b
Started on May 2, 2022, 1:17:57 PM

**Comment by apeabody** [comment]
Failed: 1de39e82
Started on May 2, 2022, 1:37:21 PM

Error: Error when reading or editing BillingBudget "billingAccounts/[...]": googleapi: Error 403: Cloud Billing Budget API has not been used in project [...] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/billingbudgets.googleapis.com/overview?project=[...] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by apeabody** [comment]
Successful: 460b1df3
Started on May 2, 2022, 2:11:15 PM

**Comment by apeabody** [comment]
Successful: c280f821
Started on May 2, 2022, 3:58:55 PM

**Comment by apeabody** [comment]
Successful: cfaa3f59
Started on May 2, 2022, 4:25:28 PM

**Comment by apeabody** [comment]
Successful: 497b6dc6
Started on May 2, 2022, 5:36:20 PM

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by apeabody** [comment]
Successful: 31fc7230
Started on May 3, 2022, 8:32:13 AM

**Comment by apeabody** [comment]
Successful: 00aa8378
Started on May 3, 2022, 9:05:24 AM

**Comment by apeabody** [comment]
Testing complete

**Pull request closed without merging**
