### PR TITLE
Enable multiple host networks

### PR DESCRIPTION
**Pull request by ideasculptor**
The project factory modules can only attach to a single host project at create-time, but it is not uncommon for a service project to be associated with more than one host project.  This PR breaks out the resources that set up VPC sharing into their own module, so that it can be called repeatedly in order to attach multiple host projects.  The project-factory modules, themselves, have unchanged behaviour, but a caller now has flexibility to add several more host projects (and subnets) to a service project after the project factory module returns.  This new module probably deprecates the terraform-google-modules/terraform-google-network/google//modules/fabric-net-svpc-access module.

fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/306

### CODE REVIEW

**Comment by ideasculptor** [comment]
Details about that test failure would be handy. If there's a way you can give me read-only access to cloud-build trigger output, that would sure be handy.  I'd be happy to provide the address of a gsuite group or you can use my email address, which you already have. Running them locally just to see the output is both time consuming and not necessarily effective, depending on the failure.

**Comment by ideasculptor** [comment]
The error I'm seeing is as follows - it seems unlikely to be related to the PR, since it isn't even getting to the point where the created project can have anything applied to it. I've run it several times with the same result.

```
       module.project-factory.module.project-factory.google_project.main: Still creating... [9m59s elapsed]
       module.project-factory.module.project-factory.google_project.main: Still creating... [10m9s elapsed]
       
       Error: Error enabling the Compute Engine API required to delete the default network: Error waiting for Enable Project "pf-ci-test-minimal-ffc7ac-a696" Services: [compute.googleapis.com]: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 10m0s)
       
         on ../../../modules/core_project_factory/main.tf line 114, in resource "google_project" "main":
        114: resource "google_project" "main" {
       
```

**Comment by morgante** [comment]
GCP doesn't support associating a service project with multiple host projects: "each service project can only be attached to a single host project" from https://cloud.google.com/vpc/docs/shared-vpc

**Comment by ideasculptor** [comment]
Well, that's an annoying oversight.  It was a gcloud sales engineer who suggested I structure things with a 'shared service project' (his words, IIRC) in the first place, a couple of months ago, so it never even occurred to me to verify that it was supported.  I just assumed...  Oh well.

**Comment by morgante** [comment]
I'd assume he meant a shared host project (where you can host shared services).

**Pull request closed without merging**
