### PR TITLE
feat(TPG >5.22)!: added vpc sc dry run mode option

### LINKED ISSUE #674: export bucket_name in output
### TL;DR

Module output should export bucket_name too, to make further operations on the created bucket easier. (For example, bucket IAM configurations.) Without exporting bucket_name, operations that depends on the created bucket will either need a `trimprefix(module.project-factory.project_bucket_url[0], "gs://")` in bucket_name argument or a `depend_on` explicitly.

### Terraform Resources

_No response_

### Detailed design

_No response_

### Additional information

_No response_

### LINKED ISSUE #893: Add option to add project in VPC SC in Dry Run Mode
### TL;DR

Add option to add project in VPC SC in Dry Run Mode

### Terraform Resources

_No response_

### Detailed design

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by imrannayer**
Fix #893 
fix #674

### CODE REVIEW

**Comment by imrannayer** [comment]
@bharathkkb plz review

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @imrannayer

**Comment by imrannayer** [comment]
@bharathkkb can u plz run the integration test again?
Thanks

**Pull request merged**
