### PR TITLE
Add ability to automatically generate the changelog

### PR DESCRIPTION
**Pull request by thefirstofthe300**
Adds the necessary logic to generate a changelog using the
auto-changelog tool.

### CODE REVIEW

**Comment by aaron-lane** [comment]
Given the unpredictable sources and quality of commit messages in the repository, I don't consider this to be a feasible undertaking at present.

**Comment by morgante** [comment]
@aaron-lane I think if this is driven solely by pull requests (not commit messages) it could actually work well.

**Comment by aaron-lane** [comment]
@morgante alrighty then!
@thefirstofthe300 besides rebasing, is this ready for review?

**Comment by thefirstofthe300** [comment]
If we are going to go based off PRs, this particular tool isn't going to be the right one for the job. At some point when I get some time, I'll switch to using a more appropriate tool and update this PR.

**Pull request closed without merging**
