### PR TITLE
use count instead of for_each to support conditional enabling

### PR DESCRIPTION
**Pull request by milesmatthias**
Addresses issues discovered in https://github.com/terraform-google-modules/terraform-google-memorystore/pull/15

### CODE REVIEW

**Comment by morgante** [comment]
We specifically didn't do this because count causes issues with reordering APIs.

Could we combine count *and* for_each?

**Comment by milesmatthias** [comment]
No, TF doesn't allow combining `count` and `for_each`: https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings

**Comment by milesmatthias** [comment]
The other option here is to instruct users to use this module conditionally by passing in an empty list, something like this:

```
  activate_apis = var.enable_apis == "true" ? [
    "redis.googleapis.com",
  ] : []
```

**Comment by morgante** [comment]
Could we create a local which simply does that, then for_each over the local?

**Comment by milesmatthias** [comment]
I tried that approach, and it generates the same error.

**Comment by morgante** [comment]
Ok I'm going to try some possible solutions myself.

**Comment by morgante** [comment]
@milesmatthias PTAL at #303 and confirm it works for your module.

**Pull request closed without merging**
