### PR TITLE
chore: add wait to test/setup to reduce test flakes

### PR DESCRIPTION
**Pull request by apeabody**
chore: add wait to test/setup to reduce test flakes

feat: update test/setup to pfactory 13.0

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/app_engine
Success!
 The configuration is valid.
terraform_validate ./examples/budget_project
Success!
 The configuration is valid.
terraform_validate ./examples/essential_contacts
Success!
 The configuration is valid.
terraform_validate ./examples/fabric_project
Success!
 The configuration is valid.
terraform_validate ./examples/gke_shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/group_project
Success!
 The configuration is valid.
terraform_validate ./examples/project-hierarchy
Success!
 The configuration is valid.
terraform_validate ./examples/project_services
Success!
 The configuration is valid.
terraform_validate ./examples/quota_project
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/simple_project
Success!
 The configuration is valid.
terraform_validate ./modules/app_engine
Success!
 The configuration is valid.
terraform_validate ./modules/budget
Success!
 The configuration is valid.
terraform_validate ./modules/core_project_factory
Success!
 The configuration is valid.
terraform_validate ./modules/essential_contacts
Success!
 The configuration is valid.
terraform_validate ./modules/fabric-project
Success!
 The configuration is valid.
terraform_validate ./modules/gsuite_enabled
Success!
 The configuration is valid.
terraform_validate ./modules/gsuite_group
Success!
 The configuration is valid.
terraform_validate ./modules/project_services
Success!
 The configuration is valid.
terraform_validate ./modules/quota_manager
Success!
 The configuration is valid.
terraform_validate ./modules/shared_vpc_access
Success!
 The configuration is valid.
terraform_validate ./modules/svpc_service_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/app_engine
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/budget
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/dynamic_shared_vpc
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/fabric_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/full
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/minimal
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/vpc_sc_project
Success!
 The configuration is valid.
terraform_validate ./test/setup
╷
│
 
Error: 
Invalid reference
│
 
│
 
  on main.tf line 60, in resource "time_sleep" "wait_180_seconds":
│
 
  60:   depends_on = [
pfactory_project
]
│
 
│
 
A reference to a resource type must be followed by at least one attribute
│
 
access, specifying the resource name.
╵
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/app_engine
Success!
 The configuration is valid.
terraform_validate ./examples/budget_project
Success!
 The configuration is valid.
terraform_validate ./examples/essential_contacts
Success!
 The configuration is valid.
terraform_validate ./examples/fabric_project
Success!
 The configuration is valid.
terraform_validate ./examples/gke_shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/group_project
Success!
 The configuration is valid.
terraform_validate ./examples/project-hierarchy
Success!
 The configuration is valid.
terraform_validate ./examples/project_services
Success!
 The configuration is valid.
terraform_validate ./examples/quota_project
Success!
 The configuration is valid.
terraform_validate ./examples/shared_vpc
Success!
 The configuration is valid.
terraform_validate ./examples/simple_project
Success!
 The configuration is valid.
terraform_validate ./modules/app_engine
Success!
 The configuration is valid.
terraform_validate ./modules/budget
Success!
 The configuration is valid.
terraform_validate ./modules/core_project_factory
Success!
 The configuration is valid.
terraform_validate ./modules/essential_contacts
Success!
 The configuration is valid.
terraform_validate ./modules/fabric-project
Success!
 The configuration is valid.
terraform_validate ./modules/gsuite_enabled
Success!
 The configuration is valid.
terraform_validate ./modules/gsuite_group
Success!
 The configuration is valid.
terraform_validate ./modules/project_services
Success!
 The configuration is valid.
terraform_validate ./modules/quota_manager
Success!
 The configuration is valid.
terraform_validate ./modules/shared_vpc_access
Success!
 The configuration is valid.
terraform_validate ./modules/svpc_service_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/app_engine
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/budget
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/dynamic_shared_vpc
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/fabric_project
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/full
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/minimal
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/vpc_sc_project
Success!
 The configuration is valid.
terraform_validate ./test/setup
╷
│
 
Error: 
Invalid reference
│
 
│
 
  on main.tf line 60, in resource "time_sleep" "wait_180_seconds":
│
 
  60:   depends_on = [
pfactory_project
]
│
 
│
 
A reference to a resource type must be followed by at least one attribute
│
 
access, specifying the resource name.
╵
 ```

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@apeabody
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
