### PR TITLE
1.0 - G Suite Refactor

### PR DESCRIPTION
**Pull request by morgante**
This PR is to track the final merge of the G Suite refactor and release.

Fixes/changes should be done as PRs against 1.0-rc1.

### CODE REVIEW

**Comment by morgante** [comment]
Sadly it looks like there are still issues with the migrator script. Here's the plan after I ran it:

```
  - module.project-gke-development.google_project_iam_member.gsuite_group_role

  - module.project-gke-development.google_service_account_iam_member.service_account_grant_to_group

  - module.project-gke-development.module.project-factory.google_project_iam_member.controlling_group_vpc_membership

  - module.project-gke-development.module.project-factory.google_project_iam_member.controlling_group_vpc_membership[2]

  - module.project-gke-development.module.project-factory.google_project_iam_member.controlling_group_vpc_membership[3]

  + module.project-gke-development.module.project-factory.google_project_iam_member.gsuite_group_role
      id:                        <computed>
      etag:                      <computed>
      member:                    "group:gcp-fnd-developers@clearify.co"
      project:                   "clf-kubernetes-dev"
      role:                      "roles/editor"

  + module.project-gke-development.module.project-factory.google_service_account_iam_member.service_account_grant_to_group
      id:                        <computed>
      etag:                      <computed>
      member:                    "group:gcp-fnd-developers@clearify.co"
      role:                      "roles/iam.serviceAccountUser"
      service_account_id:        "projects/clf-kubernetes-dev/serviceAccounts/project-service-account@clf-kubernetes-dev.iam.gserviceaccount.com"

  + module.project-gke-development.module.project-factory.null_resource.preconditions
      id:                        <computed>
      triggers.%:                "5"
      triggers.billing_account:  "018E0A-48857B-79EB94"
      triggers.credentials_path: "/Users/morgantep/code/google/foundation/clearify/sa-key.json"
      triggers.folder_id:        "folders/748369303909"
      triggers.org_id:           "816421441114"
      triggers.shared_vpc:       "clf-shared-net-host"
```

**Comment by morgante** [comment]
I've tested again and everything seems to work.

**Comment by sosimon** [comment]
I've tested the migration successfully against a test project based on the `simple_project` example (no gsuite resources).

**Comment by jeffmccune** [comment]
I tested this on a simple-sample-project as well, with a single GCE instance running which isn't managed by Terraform.

I ran into the following error at the `terraform init` step of [Locally download your state file](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/1.0-rc1/docs/upgrading_to_project_factory_v1.0.md#locally-download-your-terraform-state), which is a result of appending to an existing state file:

```
terraform init
Initializing modules...
- module.project-factory
- module.project-factory.project-factory
- module.project-factory.project-factory.gsuite_group
Error refreshing state: Decoding state file version failed: invalid character '{' after top-level value
```

**Comment by jeffmccune** [comment]
I initial started the migration in the root directory of the `terraform-google-project-factor` module, which seems to work OK for awhile, but it became clear to me after executing `terraform state pull >> terraform.tfstate` that I should be running the steps with a CWD of the root module.

Suggest clarifying the migrate.py script should be downloaded to the root module directory and subsequent commands executed from there.

**Comment by jeffmccune** [comment]
Suggestion for the troubleshooting section:

```
terraform state pull >> terraform.tfstate
Empty state (no state)
```

This may mean the current directory is something other than the root module directory.  Suggested action: make sure the migration steps are run from the root module directory.

**Comment by jeffmccune** [comment]
Other than my comments above I was able to migrate the simple project successfully:

```
Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

Outputs:

domain_example = emanon.com
project_info_example = sandbox-4a42
```

**Comment by brandoconnor** [comment]
I did a run through on a fresh project created with `v0.3.0` containing no resources. Here's what I saw:

1. The project created fine upon a second `apply` but when running `terraform init -upgrade`, I found `org_id` became a required variable:
    ```
    Initializing the backend...
    
    Error: module "project_factory_migration": missing required argument "org_id"
    ```
The fix: added `org_id` and a valid value.
Result: it worked.
2. Further on, when checking the generated state vs the plan, the following resource showed:
    ```
    + module.project_factory_migration.module.project-factory.null_resource.preconditions
    ...
    Plan: 1 to add, 0 to change, 0 to destroy.
    ```
Not necessarily bad, just something different than what's documented.

That was all that I saw deviate from the migration happy path. All else succeeded against `1.0-rc1`.

**Comment by morgante** [comment]
It looks like attempting to merge in master somehow broke this. The issue is somewhere in here: https://github.com/terraform-google-modules/terraform-google-project-factory/pull/94/files/bb2b84289d32555a2e1976a89f4ae66dc38da526..4ff2d26bc1a6c4ac47a4e3c4326421bbba217b9b

**Comment by morgante** [comment]
Sadly it looks like this is still breaking CI:

```
       Error: Error running plan: 5 error(s) occurred:
       
       * module.project-factory.module.project-factory.google_service_account_iam_member.service_account_grant_to_group: google_service_account_iam_member.service_account_grant_to_group: value of 'count' cannot be computed
       * google_service_account_iam_member.additive_service_account_grant_to_group: google_service_account_iam_member.additive_service_account_grant_to_group: value of 'count' cannot be computed
       * module.project-factory.module.project-factory.google_compute_subnetwork_iam_member.group_role_to_vpc_subnets: google_compute_subnetwork_iam_member.group_role_to_vpc_subnets: value of 'count' cannot be computed
       * module.project-factory.module.project-factory.google_storage_bucket_iam_member.group_storage_admin_on_project_bucket: google_storage_bucket_iam_member.group_storage_admin_on_project_bucket: value of 'count' cannot be computed
       * module.project-factory.module.project-factory.google_project_iam_member.gsuite_group_role: google_project_iam_member.gsuite_group_role: value of 'count' cannot be computed
```

**Comment by morgante** [comment]
It looks like we still don't have the group logic quite right. We need parity with the current project factory.

To be specific, if I am using the non-G Suite project factory, I have two options:
1. Pass in a `group_name` and it will be granted all the appropriate roles (ex. https://github.com/terraform-google-modules/terraform-google-project-factory/blob/ab4953980116a902f2fa1f9349a3bcb3fec4d06a/modules/core_project_factory/main.tf#L203)
2. Don't pass in a `group_name` and no roles will be added

For the G Suite version, there are 4 options:
1. Pass in a `group_name` and `create_group = false` => grant the roles to the group
2. Pass in a `group_name` and `create_group = true` => create the given group name and grant it the required roles
3. Don't pass in a group_name and `create_group = true` => creates a group named `project_name-editors` and grants it the required roles.
4. Don't pass in a group_name and `create_group = false` -> no group roles granted

**Pull request merged**
