### PR TITLE
Issue terraform-google-modules#205 gsuite_enabled should not require …

### LINKED ISSUE #205: gsuite_enabled should not require credentials_path
The `credentials_path` for the `gsuite_enabled` module should not be required since it is only being passed to the core_project_factory doesn't require it.

### PR DESCRIPTION
**Pull request by bbrouwer**
Fixes #205

### CODE REVIEW

**Comment by bbrouwer** [comment]
I'm struggling getting `make generate_docs` to work. This apparently does nothing for me: `go get -v github.com/segmentio/terraform-docs`

Which probably explains these errors:
```
Generating markdown docs with terraform-docs
terraform-docs markdown .
test/make.sh: line 135: terraform-docs: command not found
Traceback (most recent call last):
  File "helpers/combine_docfiles.py", line 52, in <module>
    re.DOTALL
AttributeError: 'NoneType' object has no attribute 'groups'
```

And I have this:
```
$ go version
go version go1.10.4 linux/amd64
```

Are there docs somewhere showing how to set this up?

**Comment by morgante** [comment]
If `go get` isn't working, you could try downloading the binary directly to your path: https://github.com/segmentio/terraform-docs/releases

**Comment by bbrouwer** [comment]
I ran `make generate_docs` but there are many more doc changes than what can be explained by my changes. Do you want me to commit all the unrelated doc changes as well? Do you need me to cherry-pick doc changes to just the ones related to my changes?

**Comment by morgante** [comment]
@bbrouwer If you include them all, that's fine. Thanks.

**Pull request merged**
