### PR TITLE
fix: make org id optional

### LINKED ISSUE #808: make org id optional
### TL;DR

Org id could be made optional when folder is used.

### Terraform Resources

_No response_

### Detailed design

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by abhikaddy**
Attempt to fix #808 to make or id optional.

### CODE REVIEW

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @abhikaddy! It appears the `org_id` variable itself is required, perhaps add a default value of `null`?  https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/variables.tf#L29

**Comment by abhikaddy** [comment]
Thanks @apeabody for the review.
Requested changes made.

**Comment by abhikaddy** [comment]
@apeabody Can I get gcbrun?

**Comment by abhikaddy** [comment]
Hi Good Day!
Can I get a merge? @apeabody @g-awmalik @bharathkkb

**Comment by apeabody** [comment]
@bharathkkb - Could you also review given the central nature of `terraform-google-project-factory`?

**Review by bharathkkb — APPROVED** [review]
Sorry for the delay!

**Pull request merged**
