### PR TITLE
fix: explicit depends on for budget project data source

### PR DESCRIPTION
**Pull request by bharathkkb**
fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/555

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/budget/main.tf
--- old/modules/budget/main.tf
+++ new/modules/budget/main.tf
@@ -30,7 +30,7 @@
 }
 
 data "google_project" "project" {
-  depends_on = [ var.projects ]
+  depends_on = [var.projects]
   count      = length(var.projects)
   project_id = element(var.projects, count.index)
 }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Review by morgante — APPROVED** [review]

**Comment by morgante** [comment]
@bharathkkb Were you able to reproduce and confirm this fixes it?

**Comment by bharathkkb** [comment]
@morgante I tested `dynamic_shared_vpc` locally. 
On `main` when I plan, it errors with 
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
------------------------------------------------------------------------
Error: the user does not have permission to access Project "b-pf-ci-shared2-svc-ab19df" or it may not exist



Error: the user does not have permission to access Project "pf-ci-shared2-svc-ab19df" or it may not exist

```
With this fix looks like it is deferring the read correctly
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

...

  # module.example.module.host-project.module.budget.data.google_project.project[0] will be read during apply
  # (config refers to values not yet known)
 <= data "google_project" "project"  {
      + auto_create_network = (known after apply)
      + billing_account     = (known after apply)
      + folder_id           = (known after apply)
      + id                  = (known after apply)
      + labels              = (known after apply)
      + name                = (known after apply)
      + number              = (known after apply)
      + org_id              = (known after apply)
      + project_id          = (known after apply)
      + skip_delete         = (known after apply)
    }
```
and looks like the integrations tests passed too.

**Comment by morgante** [comment]
Great, thanks for the fix.

**Pull request merged**
