### PR TITLE
Add budget notification channel

### PR DESCRIPTION
**Pull request by davidholsgrove**
Allow configuring billing budget with monitoring notification channels.

Fixes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/455

### CODE REVIEW

**Comment by davidholsgrove** [comment]
Hi @adrienthebo / @morgante - any chance of a review on this PR?
The budget alerts through Monitoring Notification channel email appear to be more useful out-of-the-box than the pub/sub method, due to the budget publishing messages multiple times a day, not just at budget threshold.

**Comment by morgante** [comment]
Thanks for the contribution! @davidholsgrove Do you think we should accept the email and create the channel inline within the module?

**Comment by davidholsgrove** [comment]
> 
> 
> Thanks for the contribution! @davidholsgrove Do you think we should accept the email and create the channel inline within the module?

Good question - I followed the approach in the module currently, where we don't create the pub/sub resources, and just take the topic name as a var.

I think creating the notification channel in-module might be more difficult, as in practice if people follow https://cloud.google.com/monitoring/workspaces#monitored-projects the monitoring workspace project will be different from the budget project

**Review by morgante — APPROVED** [review]

**Comment by morgante** [comment]
@davidholsgrove Good point, I think this is fine as is. We could adjust this later if need be.

**Pull request merged**
